import { RestApi } from '@servicenow/sdk/core'
import {
    ping,
    postBatch,
    getStructureHandler,
    getAssetTypesHandler,
    promoteBatchHandler,
    getDashboardHandler,
    promoteDashboardHandler,
    syncAssetTypesHandler,
    lookupAssetHandler,
} from '../../server/rest/handlers'
import { restApiAcl, restPromoteAcl } from '../security/acls.now'

RestApi({
    $id: Now.ID['nowrfid-api'],
    name: 'NowRFID API',
    serviceId: 'nowrfid',
    shortDescription: 'Receives RFID / barcode / QR capture batches from the NowRFID Android app',
    consumes: 'application/json',
    produces: 'application/json',
    enforceAcl: [restApiAcl],
    routes: [
        {
            $id: Now.ID['nowrfid-api-dashboard'],
            name: 'dashboard',
            method: 'GET',
            path: '/dashboard',
            script: getDashboardHandler,
            authentication: true,
            authorization: true,
            enforceAcl: [restPromoteAcl],
            produces: 'application/json',
            shortDescription: 'Admin: aggregates for the NowRFID dashboard (Painel)',
        },
        {
            $id: Now.ID['nowrfid-api-dashboard-promote'],
            name: 'dashboard-promote',
            method: 'POST',
            path: '/dashboard/promote',
            script: promoteDashboardHandler,
            authentication: true,
            authorization: true,
            enforceAcl: [restPromoteAcl],
            consumes: 'application/json',
            produces: 'application/json',
            shortDescription: 'Admin: create assets for classified items, optionally only in the given rooms ({"locations":[sys_id]})',
        },
        {
            $id: Now.ID['nowrfid-api-promote'],
            name: 'promote',
            method: 'POST',
            path: '/batch/{batch_sys_id}/promote',
            script: promoteBatchHandler,
            authentication: true,
            authorization: true,
            enforceAcl: [restPromoteAcl],
            produces: 'application/json',
            shortDescription: 'Admin: create assets for every classified, not yet promoted item of a batch',
        },
        {
            $id: Now.ID['nowrfid-api-structure'],
            name: 'structure',
            method: 'GET',
            path: '/structure',
            script: getStructureHandler,
            authentication: true,
            authorization: true,
            enforceAcl: [restApiAcl],
            produces: 'application/json',
            shortDescription: 'Location tree (entities and their rooms, or x_snc_nowrfid.location_root when set) plus stockrooms. Optional ?since=ISO8601 for delta sync in fixed-root mode',
        },
        {
            $id: Now.ID['nowrfid-api-asset-types'],
            name: 'asset-types',
            method: 'GET',
            path: '/asset-types',
            script: getAssetTypesHandler,
            authentication: true,
            authorization: true,
            enforceAcl: [restApiAcl],
            produces: 'application/json',
            shortDescription: 'Active asset types (Tipos de bem) with SIAF accounts and models for the capture menu',
        },
        {
            $id: Now.ID['nowrfid-api-asset-types-sync'],
            name: 'asset-types-sync',
            method: 'POST',
            path: '/asset-types/sync',
            script: syncAssetTypesHandler,
            authentication: true,
            authorization: true,
            enforceAcl: [restPromoteAcl],
            produces: 'application/json',
            shortDescription: 'Admin: regenerate the Tipos de bem from the model categories with a SIAF account of the discipline',
        },
        {
            $id: Now.ID['nowrfid-api-lookup'],
            name: 'lookup',
            method: 'GET',
            path: '/lookup',
            script: lookupAssetHandler,
            authentication: true,
            authorization: true,
            enforceAcl: [restApiAcl],
            produces: 'application/json',
            shortDescription: 'Find where an asset is registered, by ?epc=, ?tid= (tag registry) or ?barcode= (asset_tag / serial number)',
        },
        {
            $id: Now.ID['nowrfid-api-ping'],
            name: 'ping',
            method: 'GET',
            path: '/ping',
            script: ping,
            authentication: true,
            authorization: true,
            enforceAcl: [restApiAcl],
            shortDescription: 'Connectivity / credential check',
        },
        {
            $id: Now.ID['nowrfid-api-batch'],
            name: 'batch',
            method: 'POST',
            path: '/batch',
            script: postBatch,
            authentication: true,
            authorization: true,
            enforceAcl: [restApiAcl],
            consumes: 'application/json',
            produces: 'application/json',
            shortDescription: 'Create a scan batch with its items (idempotent on batch.client_batch_id)',
            requestExample:
                '{"batch":{"client_batch_id":"4f1c...","device_id":"pixel-7","reader_mac":"D7:3B:AA:46:B4:E0","captured_at":"2026-09-24T18:30:00Z","app_version":"0.1.0","notes":""},"items":[{"client_item_id":"a1","capture_type":"rfid","operation":"read","epc":"E2004000780600801570752E","rssi":"-55.3","read_count":3,"captured_at":"2026-09-24T18:29:58Z"}]}',
        },
    ],
})
